### PR TITLE
Remove unsound code and unsafe APIs

### LINKED ISSUE #1: Soundness issues in this crate
Hi, I just came across this crate and noticed it has several soundness issues. I wrote the text about `Arc::SharedPtr<T>`, but since it shares much the same codebase as `Rc::SharedPtr<T>`, all of the criticisms here apply there too and must equally be fixed.

## Transmuting `repr(Rust)`

[In `SharedPtr::assume_init`](https://github.com/luyikk/SharedPtr/blob/966a2a73621e0a147bf353fb5523e9d58f92748b/src/Arc.rs#L41) it is assumed that `Self` (that is, `SharedPtr<T>`) is able to be soundly transmuted to `Arc<T>`. However, may not be the case because [`#[repr(Rust)]` types (like your `SharedPtr<T>` type) have an intentionally unspecified layout](https://doc.rust-lang.org/reference/type-layout.html#the-default-representation). This means that `SharedPtr<T>` may be of a totally different layout than `Arc<T>` and thus transmuting between them would be Undefined Behaviour. Now as it happens, `transmute` comes with a size check so if `SharedPtr<T>` _does_ end up with a different layout your code would fail to compile, so it's technically not unsound - but it's still extremely dubious and fragile and should be avoided.

One easy fix of this is to annotate `struct SharedPtr<T>` with `#[repr(transparent)]` which would force it to have the exact same layout as its only field, `Arc<T>`, thus making transmutes between the two types OK. However really you should not be using a `transmute` here at all - there are larger issues with the type which I write about later.

## Assuming `Arc<T>`'s layout

[In `SharedPtr::is_null`](https://github.com/luyikk/SharedPtr/blob/966a2a73621e0a147bf353fb5523e9d58f92748b/src/Arc.rs#L58) you find out whether the `MaybeUninit` has been created with `zeroed()` by casting `*const Arc<T>` to `*const usize` and then checking whether the `usize` is zero. This is unsound because `Arc<T>` is `#[repr(Rust)]` and therefore there is no guarantee that its first field is a pointer - Rust could choose to insert an arbitrary number of padding bytes at the start which would break your code. `Arc<T>` also does not guarantee that `0` is not a valid value for the type, so you cannot rely on that being true - it's possible that a valid value of `Arc<T>` would have an identical bitpattern to `MaybeUninit::zeroed()`.

## Obtaining `&mut T` from `&T`

In [`SharedPtr::get_mut_ref`](https://github.com/luyikk/SharedPtr/blob/966a2a73621e0a147bf353fb5523e9d58f92748b/src/Arc.rs#L81) you get an `&mut T` from an `&Arc<T>` by going `&T -> *const T -> *mut T -> &mut T`. **This is very certainly and very severly Undefined Behaviour (UB) _in all circumstances_**. [The Nomicon is extremely clear about this](https://doc.rust-lang.org/nomicon/transmutes.html):

> * Transmuting an `&` to `&mut` is UB.
>     * Transmuting an `&` to `&mut` is always UB.
>     * No you can't do it.
>     * No you're not special.

Your set of pointer casts amounts to a transmute in that code, and is therefore definitely and totally UB - even though the function is `unsafe`, there is _literally no way to call that function soundly_ - it basically amounts to a poor redefinition of [`std::hint::unreachable_unchecked`](https://doc.rust-lang.org/stable/std/hint/fn.unreachable_unchecked.html). The lesson here is that if you have an `&T`, there is _no possible way_ to get an `&mut T` from it, no matter how you frame it - it's _always_ UB.

If you want to provide that API, you would have to use one of `Arc`'s methods that explicitly doesn't give you an `&T`, but gives you a pointer that has the ability to be upgraded to a `&mut T`. Luckily, it has an API perfect for this: [`Arc::as_ptr`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.as_ptr). So you _could_ (and I'm _not_ saying you should, for reasons below) rewrite that function like this:

```rs
    pub unsafe fn get_mut_ref(&self)->&mut T {
        &mut *Arc::as_ptr(&**self)
    }
```

And that _would_ avoid the problem of calling the function being insta-UB.

**However**, I question why you need this API in the first place. It ends up being very `unsafe` to use, as the caller needs to uphold _all_ of these preconditions:

1. There must be no other `SharedPtr<T>`s that access the value while the `&mut T` exists.
2. The `SharedPtr<T>` itself must not access the value while the `&mut T` exists.

If either of those two preconditions are violated _at any point_, you have instant UB in the caller. This function is incredibly easy to misuse, and as such I would **strongly advise against** putting it in your public API - there's a reason `Arc` doesn't have it.

If you need to provide something like it, do implement something like [`Arc::get_mut`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.get_mut) which is a _safe_ API with a very similar purpose. By:

1. Requiring the `Arc`'s ref-count to be 1, and
2. Requiring `&mut` access to the `Arc` itself

Both those two issues above are statically guaranteed not to happen. It is a far safer and better API than the one you have right now.

## `transmute_copy`ing `repr(Rust)`

This is effectively the first point, but this time it is definitively unsound because you write code that amounts to a `transmute_copy`, which side-steps the size sanity check that `transmute` does. In [the implementation of `From<Arc<T>>` for `SharedPtr<T>`](https://github.com/luyikk/SharedPtr/blob/966a2a73621e0a147bf353fb5523e9d58f92748b/src/Arc.rs#L148) you interpret an `&Arc<T>` as a `&SharedPtr<T>` and then `ptr::read` it. Like before, this is unsound because `SharedPtr<T>` is `#[repr(Rust)]` and therefore does not necessarily have the same layout as `Arc<T>`, so it's Undefined Behaviour to treat it as an `Arc<T>`.

To give an example of what can go wrong: it would be totally valid for the Rust compiler to lay out `SharedPtr<T>` as having 1024 unused bytes of padding before the `Arc<T>`, and 1024 bytes afterwards as well for good measure. Therefore calling `ptr.read()` would attempt to read `1024 + 8 + 1024` bytes from `ptr` - but `ptr` would only point to the 8 bytes of the `Arc<T>`! So you'd end up reading 2048 bytes from some random location in memory, some of which would be interpreted as a pointer for an `Arc<T>`, and at that point all hell breaks loose. Best case scenario is that you end up reading into an invalid memory address and the OS terminates your process, worst case scenario is that you're able to read those bytes and the pointer you _think_ is an `Arc<T>` turns out to be valid and you end up with critical security vulnerabilities as now you're writing some arbitrary data into an arbitrary part of memory.

But all of this is beside the main point: it isn't bad because of what could happen, it's bad because Rust has defined it to be UB and you must obey those laws, there's no way around it.

## Reading from a moved memory location

But that's not even the most egregious thing in that function, because that `ptr::read` also does something else - it reads from a memory location that has been previously moved out of. On [line 146](https://github.com/luyikk/SharedPtr/blob/966a2a73621e0a147bf353fb5523e9d58f92748b/src/Arc.rs#L146) `ptr` is defined as pointing to the `r` local variable - this means that if `r` is ever moved out of, `ptr` becomes invalid and must not be used from that point onward. So what happens next?

> ```rs
> std::mem::forget(r);
> ```

This will move out of the `r` variable, invalidating any and all pointers that were pointing to it. This means that later calling `.read()` on a pointer that _used_ to point to `r` is most definitely and certainly Undefined Behaviour and **must** be avoided.

All this unsound code is rather unnecessary too, since that entire function can be replaced with simply:

```rs
Self {
    rc: MaybeUninit::new(r),
}
```

Which is 100% safe and sound, as well as shorter and easier to read.

## `MaybeUninit` is unnecessary

Currently the crate is built around a `MaybeUninit<Arc<T>>` to provide what is essentially an optional `Arc`. But that is actually not necessary at all, `Option<Arc<T>>` can be used equally well and with zero `unsafe` code, instantly fixing all of the problems above.

`Option<Arc<T>>` is exactly the same size as `MaybeUninit<Arc<T>>` and `Arc<T>`, because the Rust compiler is able to tell automatically that zero is not a valid value for `Arc<T>`, and therefore if it sees a zero it can infer that it must be `Option::None` instead. This process is called [niche optimization](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#niche) and it is a very powerful feature of Rust. Also note that it's not guaranteed to happen, but at the same time you don't need the guaratee that `SharedPtr<T>` is the same size as `Arc<T>` - it's just a nice-to-have optimization.

I will create a PR to replace the use of `MaybeUninit` with `Option`s, removing all the unnecessary `unsafe` in the process.

## Advice

Unsound code is treated very seriously in Rust -  after all, it's what Rust was designed to protect against. I would advise reading about [what behavior is considered undefined](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) and reading through the [Nomicon](https://doc.rust-lang.org/nomicon/) too, because writing _correct_ `unsafe` code is very difficult and should not be done without a significant amount of caution and understanding of the area.

I would also advise writing many tests for every bit of `unsafe` you write, then running it through [Miri](https://github.com/rust-lang/miri). Miri is a tool for running your code and dynamically checking your `unsafe` to make sure you don't cause Undefined Behaviour. It's not totally exhaustive and there are still many cases it won't catch, but it is incredibly helpful for many many cases and can help catch out simple mistakes like these.

### PR DESCRIPTION
**Pull request by SabrinaJewson**
Fixes: #1

I also ran rustfmt on the code so that formatting would be made consistent - only pay attention to the second commit since the first is just formatting changes.

### CODE REVIEW

**Comment by luyikk** [comment]
Yes, merge first. I have to test the compatibility of existing projects.

**Comment by luyikk** [comment]
///# Safety
    /// Rc::get_mut Too strict, resulting in limited function,
    /// we need an unsafe way to be consistent with the SharedPtr
    #[inline]
    pub unsafe fn get_mut_ref(&self) -> &mut T {
        &mut *(self.as_ref() as *const T as *mut T)
    }

Because `Rc::get_mut` check `Rc::weak_count(this) == 0 && Rc::strong_count(this) == 1`
this does not meet my design requirements.

I don't think there are any other problems, so it can be compatible with my project.

**Comment by luyikk** [comment]
Additionally add `pub fn get_mut(&mut self) -> &mut T`  this is the version you submitted, rename is `get_mut`.
commit version `0.3.0` to crates.io

**Comment by SabrinaJewson** [comment]
> Because `Rc::get_mut` check `Rc::weak_count(this) == 0 && Rc::strong_count(this) == 1`
> this does not meet my design requirements.

Can you at least then expose an API with a more similar design to `get_mut_unchecked` then? For the reasons I outlined in #1, `get_mut_ref` is very prone to errors.

**Comment by luyikk** [comment]
I have modified it according to your proposal and try to isolate unsafe code. Please see [https://github.com/luyikk/SharedPtr/commit/00067d01a8547263ce9f27f0ba3e5f5822ce18eb](url) for details

**Comment by SabrinaJewson** [comment]
@luyikk That's not what I was suggesting - it's fine to have that function be an inherent unsafe method of the type, the extension trait is unnecessary. The problems are that:

1. The definition of `get_mut_ref` is currently UB since it doesn't use `Arc::as_ptr`.
2. Ideally it would accept `&mut self` instead to be less error-prone.

**Pull request merged**
